
server:  port: 8888
  
spring:  cloud:    config:      server:
        encrypt:          enabled: false        git:
          uri: https://github.com/TalesC/microservice-config-repo
          search-paths: fornecedor, loja, transportador
          
          
          